server:
  port: 8085

jwt:
  signing-key: ${JWT_SIGNING_KEY:1234567890}

oauth2:
  client:
    id: ${CLIENT_ID:clientId}
    secret: ${CLIENT_SECRET:secret}
  token:
    validity-seconds:
      access: ${TOKEN_VALIDITY_ACCESS:43200}
      refresh: ${TOKEN_VALIDITY_REFRESH:2592000}
  valid-uris: ${VALID_URIS:http://localhost:8082/webjars/springfox-swagger-ui/oauth2-redirect.html,http://localhost:8088/spring-security-oauth-resource/webjars/springfox-swagger-ui/oauth2-redirect.html}
  authorized-grant-types: ${AUTHORIZED_GRANT_TYPES:password,authorization_code,refresh_token,client_credentials}
  
spring:
  profiles:
    active: ${LOGGING_MODE:dev}
  jackson:
    serialization:
      INDENT_OUTPUT: true